import json
import logging
import time
from types import SimpleNamespace
from datetime import datetime,timezone
from uuid import uuid4
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError

from app.core.exceptions import PlanningError
from app.core.provenance import canonical_hash
from app.models.operations import ForecastRunModel
from app.models.decision import DecisionRunModel
from app.repositories.idempotency import IdempotencyRepository
from app.repositories.planning import PlanningRepository
from app.services.idempotency_service import IdempotencyService
from app.services.decision.adapters.procurement_adapter import CoreProcurementAdapter
from app.services.decision.build_decision_brief import BuildDecisionBrief
from app.services.decision.completed_forecast_reader import CompletedForecastReader
from app.services.decision.explain_decision import ExplainDecision
from app.services.decision.ingredient_demand_lifecycle import IngredientDemandLifecycle
from app.services.decision.legacy_plan_compatibility import LegacyPlanCompatibility
from app.services.decision.operational_procurement_lifecycle import OperationalProcurementLifecycle
from app.services.decision.read_decision_package import ReadDecisionPackage

def now():return datetime.now(timezone.utc)
def dump(x):return json.dumps(x,ensure_ascii=False,default=str)
logger=logging.getLogger("shelfcash.planning")

class DecisionPlanningService:
 def __init__(self,factory,settings=None,llm_provider=None):
  self.factory=factory;self.settings=settings;self.llm_provider=llm_provider;self.read_decision_package=ReadDecisionPackage(factory)
  self.completed_forecast_reader=CompletedForecastReader();self.ingredient_demand=IngredientDemandLifecycle(factory,self.completed_forecast_reader);self.operational_procurement=OperationalProcurementLifecycle(factory,self.completed_forecast_reader);self.legacy_plan_compatibility=LegacyPlanCompatibility(factory,self.completed_forecast_reader,self.ingredient_demand,self.operational_procurement)
 def _forecast(self,s,store,run_id):return self.completed_forecast_reader.load(s,store,run_id)
 def generate_demand(self,store,run_id,key=None,refresh=False):return self.ingredient_demand.generate(store,run_id,key,refresh)
 def get_demand(self,store,run_id):return self.ingredient_demand.read(store,run_id)
 def generate_plans(self,store,run_id,body,key=None):return self.operational_procurement.generate(store,run_id,body,key)
 def get_plans(self,store,run_id,planning_run_id=None):return self.operational_procurement.read(store,run_id,planning_run_id)

 def create_legacy_plan(self,store,body,key=None,request_id=None):return self.legacy_plan_compatibility.create(store,body,key,request_id)
 def get_legacy_plan_metadata(self,store,rid):return self.legacy_plan_compatibility.read_metadata(store,rid)
 def get_legacy_plan_result(self,store,rid):return self.legacy_plan_compatibility.read_result(store,rid)

 def generate_decision(self,store,body,key=None):
  """Run the core path and persist one self-contained Decision Package."""
  mode=body.engine_mode or getattr(self.settings,"decision_engine_mode","legacy")
  if mode=="legacy":
   raise PlanningError("DECISION_ENGINE_LEGACY", "Use existing procurement-plan endpoints while DECISION_ENGINE_MODE=legacy.",http_status=409)
  if body.as_of_date is None:raise PlanningError("FORECAST_INPUT_INVALID","as_of_date is required.")
  endpoint=f"/api/v1/stores/{store}/decision-runs";payload=body.model_dump(mode="json");request_hash=canonical_hash(payload)
  with self.factory() as s:
   forecast,_=self._forecast(s,store,body.forecast_run_id)
   if forecast.cutoff_date!=body.as_of_date:raise PlanningError("FORECAST_INPUT_INVALID","as_of_date must equal forecast cutoff_date.",{"as_of_date":body.as_of_date,"cutoff_date":forecast.cutoff_date})
   if body.horizon_days!=forecast.horizon_days:raise PlanningError("FORECAST_INPUT_INVALID","horizon_days must equal forecast horizon.",{"horizon_days":body.horizon_days,"forecast_horizon":forecast.horizon_days})
   if key:
    repo=IdempotencyRepository(s);existing=repo.get(store_id=store,endpoint=endpoint,http_method="POST",idempotency_key=key)
    if existing is not None:
     replay=IdempotencyService(repo).register(store_id=store,endpoint=endpoint,http_method="POST",idempotency_key=key,request_hash=request_hash)
     rid=replay.record.resource_id;s.rollback();return self.get_decision(rid)
  # Decision packages must use a BOM expansion generated by the currently
  # deployed core; a completed run can otherwise retain a historical derived
  # demand payload after a deterministic BOM fix.
  self.generate_demand(store,body.forecast_run_id,refresh=True)
  with self.factory() as s:
   forecast,predictions=self._forecast(s,store,body.forecast_run_id);demands=PlanningRepository(s).demand_predictions(PlanningRepository(s).demand_run_for_forecast(forecast.forecast_run_id).ingredient_demand_run_id)
   if not demands:raise PlanningError("INGREDIENT_DEMAND_INCOMPLETE","No ingredient demand is available for decision.",http_status=409)
   rid=str(uuid4());started=time.monotonic()
   logger.info("decision_stage_started decision_run_id=%s store_id=%s stage=core_runner engine_mode=%s",rid,store,mode)
   try:
    adapter=CoreProcurementAdapter(s);result,request,baseline,scenario_metadata=adapter.optimize(store,forecast,demands,body.budget_override,body.include_open_purchase_orders,
     predictions=predictions,engine_mode=mode,scenario_count=body.scenario_count or getattr(self.settings,"decision_scenario_count",100),seed=body.random_seed if body.random_seed is not None else getattr(self.settings,"decision_random_seed",42),scenario_method=getattr(self.settings,"decision_scenario_method","residual_bootstrap"))
   except Exception as exc:
    raise PlanningError("OPTIMIZATION_INFEASIBLE","Core decision execution failed.",{"reason":str(exc)[:500]},http_status=422) from exc
   forecast_trace={"decision_run_id":rid,"requested_forecast_run_id":body.forecast_run_id,"resolved_forecast_run_id":forecast.forecast_run_id,"forecast_store_id":forecast.store_id,"forecast_cutoff_date":forecast.cutoff_date.isoformat(),"forecast_target_min":min(item.target_date for item in predictions).isoformat(),"forecast_target_max":max(item.target_date for item in predictions).isoformat(),"prediction_count":len(predictions)}
   package=self._decision_package(rid,store,forecast,mode,result,request,baseline,demands,scenario_metadata,forecast_trace,adapter.shortage_economics)
   run=DecisionRunModel(decision_run_id=rid,store_id=store,forecast_run_id=forecast.forecast_run_id,as_of_date=forecast.cutoff_date,horizon_days=forecast.horizon_days,engine_mode=mode,status=package["status"],scenario_method=package["technical_metrics"]["scenario_method"],scenario_count=package["technical_metrics"]["scenario_count"],random_seed=request.seed,recommended_strategy=package["recommended_strategy"],request_json=dump(payload),package_json=dump(package),warnings_json=dump(package["warnings"]),created_at=now(),completed_at=now())
   if key:
    repo=IdempotencyRepository(s)
    try:
     replay=IdempotencyService(repo).register(store_id=store,endpoint=endpoint,http_method="POST",idempotency_key=key,request_hash=request_hash)
    except IntegrityError:
     s.rollback()
     replay=IdempotencyService(repo).register(store_id=store,endpoint=endpoint,http_method="POST",idempotency_key=key,request_hash=request_hash)
    if replay.is_replay:
     replay_id=replay.record.resource_id;s.rollback();return self.get_decision(replay_id)
    rec=replay.record;rec.resource_type="decision_run";rec.resource_id=rid;rec.response_status=200
   s.add(run)
   s.commit()
   logger.info("decision_stage_completed decision_run_id=%s store_id=%s stage=core_runner duration_ms=%d scenario_count=%s optimizer_type=%s warning_count=%d",rid,store,int((time.monotonic()-started)*1000),package["technical_metrics"]["scenario_count"],package["technical_metrics"]["optimizer_type"],len(package["warnings"]))
  try:
   self._generate_and_persist_overall_summary(rid)
  except Exception:
   # Narrative generation is downstream metadata; a failure never invalidates
   # the deterministic Decision Run already committed above.
   logger.exception("overall_summary_persistence_failed decision_run_id=%s",rid)
  return self.get_decision(rid)

 def get_decision(self,rid):
  return self.read_decision_package.read(rid)

 def get_decision_brief(self,rid):
  return BuildDecisionBrief(self.factory,self.settings,self.llm_provider).build(rid)

 def _generate_and_persist_overall_summary(self,rid):
  """Generate exactly once after the core Decision Package is committed."""
  from app.decision_intelligence import DecisionBriefBuilder
  from app.decision_intelligence.contracts import AssistantSummary
  from app.decision_intelligence.overall_summary import OverallSummaryProvider
  from app.decision_intelligence.semantic_evidence import DecisionSemanticEvidenceBuilder
  from app.decision_intelligence.ingredient_synthesis import IngredientSynthesisProvider
  with self.factory() as s:
   run=s.get(DecisionRunModel,rid)
   if not run:return
   package=json.loads(run.package_json)
   assistant=package.get("assistant") if isinstance(package.get("assistant"),dict) else {}
   if isinstance(assistant.get("overall_summary"),dict) and isinstance(assistant.get("ingredient_synthesis"),list):return
   brief=DecisionBriefBuilder().build(s,run)
   facts=DecisionSemanticEvidenceBuilder().build(brief,package)
   summary=AssistantSummary.model_validate(assistant["overall_summary"]) if isinstance(assistant.get("overall_summary"),dict) else OverallSummaryProvider(self.llm_provider,self.settings).summarize(brief,facts)
   synthesis_provider=IngredientSynthesisProvider(self.llm_provider,self.settings)
   synthesis=synthesis_provider.synthesize(brief,facts)
   # Developer-only metadata stays in the immutable Decision Run package.  The
   # DecisionBriefBuilder reads only assistant.ingredient_synthesis, keeping
   # OpenRouter transport details and raw content out of the FE /brief contract.
   package["assistant"]={
    **assistant,
    "overall_summary":summary.model_dump(mode="json"),
    "ingredient_synthesis":[item.model_dump(mode="json") for item in synthesis],
    "ingredient_synthesis_diagnostics":synthesis_provider.last_diagnostics,
   }
   run.package_json=dump(package)
   s.commit()

 def explain_decision(self,rid,body):
  return ExplainDecision(
   BuildDecisionBrief(self.factory,self.settings,self.llm_provider),
   self.read_decision_package,self.settings,self.llm_provider,
  ).explain(rid,body)

 def what_if_decision(self,rid,body):
  """Execute an in-memory M1-M5 hypothetical; no ORM entity is mutated or persisted."""
  from app.decision_intelligence import DecisionBriefBuilder, ShelfCashDecisionIntelligenceAdapter
  from app.decision_intelligence.what_if_evidence import WhatIfNarrativeProvider, build_what_if_facts
  with self.factory() as s:
   run=s.get(DecisionRunModel,rid)
   if not run:raise PlanningError("DECISION_RUN_NOT_FOUND","Decision run not found.",{"decision_run_id":rid},http_status=404)
   baseline_package=json.loads(run.package_json)
   baseline_brief=DecisionBriefBuilder().build(s,run)
   baseline_brief=baseline_brief.model_copy(update={"evidence":ShelfCashDecisionIntelligenceAdapter().evidence_briefs(baseline_brief),"data_availability":{**baseline_brief.data_availability,"authority":"BASELINE"}})
   forecast,predictions=self._forecast(s,run.store_id,run.forecast_run_id)
   multiplier=body.demand_multiplier if body.demand_multiplier is not None else 1.0
   supplier_delay_days=body.supplier_delay_days if body.supplier_delay_days is not None else 0
   demands=[]
   for item in baseline_package.get("ingredient_demand",[]):
    demands.append(SimpleNamespace(ingredient_id=str(item["ingredient_id"]),target_date=datetime.fromisoformat(str(item["target_date"])).date(),unit=item.get("unit"),p25=float(item.get("p25",0))*multiplier,p50=float(item.get("p50",0))*multiplier,p75=float(item.get("p75",0))*multiplier,contributions_json=dump(item.get("contributions",[]))))
   if not demands:raise PlanningError("INGREDIENT_DEMAND_INCOMPLETE","Persisted decision package has no ingredient demand.",http_status=409)
   try:
    adapter=CoreProcurementAdapter(s);result,request,inventory_baseline,scenario_metadata=adapter.optimize(run.store_id,forecast,demands,body.budget_limit,True,predictions=predictions,engine_mode=run.engine_mode,scenario_count=run.scenario_count,seed=run.random_seed,scenario_method=getattr(self.settings,"decision_scenario_method","residual_bootstrap"),supplier_delay_days=supplier_delay_days)
   except Exception as exc:
    raise PlanningError("WHAT_IF_EXECUTION_FAILED","Hypothetical decision execution failed.",{"reason":str(exc)[:500]},http_status=422) from exc
   hypothetical_id=f"what-if:{rid}"
   trace={"decision_run_id":hypothetical_id,"baseline_decision_run_id":rid,"mutation_scope":"ingredient_demand","demand_multiplier":multiplier,"supplier_delay_days":supplier_delay_days,"budget_limit":body.budget_limit}
   package=self._decision_package(hypothetical_id,run.store_id,forecast,run.engine_mode,result,request,inventory_baseline,demands,scenario_metadata,trace,adapter.shortage_economics)
   if body.strategy is not None:self._select_hypothetical_strategy(package,body.strategy)
   hypothetical_run=SimpleNamespace(decision_run_id=hypothetical_id,store_id=run.store_id,forecast_run_id=run.forecast_run_id,as_of_date=run.as_of_date,horizon_days=run.horizon_days,status=package["status"],package_json=dump(package))
   hypothetical=DecisionBriefBuilder().build(s,hypothetical_run)
   hypothetical=hypothetical.model_copy(update={"evidence":ShelfCashDecisionIntelligenceAdapter().evidence_briefs(hypothetical),"data_availability":{**hypothetical.data_availability,"authority":"HYPOTHETICAL","mutation_scope":"ingredient_demand"}})
   what_if_facts=build_what_if_facts(rid,baseline_brief,hypothetical,body,baseline_package=baseline_package,hypothetical_package=package)
   explanation=WhatIfNarrativeProvider(self.llm_provider).explain(rid,what_if_facts).model_dump(mode="json")
   explanation["authority"]="HYPOTHETICAL"
   return {"decision_run_id":rid,"baseline":baseline_brief.model_dump(mode="json"),"hypothetical":hypothetical.model_dump(mode="json"),"mutations":body.model_dump(mode="json"),"mutation_facts":what_if_facts.mutation.model_dump(mode="json"),"comparison":what_if_facts.comparison.model_dump(mode="json"),"grounded_explanation":explanation,"generated_at":now()}

 @staticmethod
 def _select_hypothetical_strategy(package,strategy):
  candidate=package.get("strategies",{}).get(strategy,{})
  if candidate.get("is_feasible"):
   package["recommended_strategy"]=strategy;package["recommended_plan"]={"items":candidate.get("items",[])};package["business_metrics"]=candidate.get("business_metrics",{});package["critic"]=candidate.get("critic",{});package["stress_tests"]=candidate.get("stress_tests") or [];package["status"]="completed"
  else:
   package["recommended_strategy"]=None;package["recommended_plan"]={"items":[]};package["business_metrics"]={};package["critic"]=candidate.get("critic",{});package["status"]="completed_with_no_feasible_recommendation"

 @staticmethod
 def _package_critic(strategies,recommended):
  """Return the selected critic or a deterministic no-feasible aggregate."""
  if recommended:
   return strategies[recommended]["critic"]

  findings={};warnings=set()
  for strategy in sorted(strategies):
   critic=strategies[strategy]["critic"]
   warnings.update(critic["warnings"])
   for finding in critic["findings"]:
    code=finding["code"]
    aggregate=findings.setdefault(code,{"code":code,"severity":finding["severity"],"evidence":{"by_strategy":{}}})
    aggregate["evidence"]["by_strategy"][strategy]=finding["evidence"]
  return {
   "status":"fail",
   "findings":[findings[code] for code in sorted(findings)],
   "warnings":sorted(warnings),
   "checks":{},
   "details":{},
  }

 @staticmethod
 def _decision_package(rid,store,forecast,mode,result,request,baseline,demands,scenario_metadata=None,forecast_trace=None,shortage_economics=None):
  from app.services.business_metrics_service import build_business_metrics
  def metric(sim):
   return build_business_metrics(purchase_cost=None, simulation=sim, recommended=True)
  scenario_metadata=scenario_metadata or {};strategies={};warnings=set(scenario_metadata.get("warnings",[]));recommended=result.recommended_strategy.lower() if result.recommended_strategy else None
  for name,evaluation in result.evaluations.items():
   sim=evaluation.simulation;critic=evaluation.critic;warnings.update(evaluation.plan.warnings);warnings.update(critic.warnings)
   strategies[name.lower()]={"strategy":name.lower(),"is_feasible":critic.passed,"purchase_cost":evaluation.plan.purchase_cost,"expected_recourse_cost":evaluation.plan.expected_recourse_cost,"business_metrics":build_business_metrics(purchase_cost=evaluation.plan.purchase_cost,simulation=sim,recommended=True,risk_simulation=evaluation.risk_simulation,risk_metadata=request.risk_evaluation_metadata) if sim else {},"items":[x.model_dump(mode="json") for x in evaluation.plan.orders],"critic":{"status":"pass" if critic.passed else "fail","findings":[{"code":x,"severity":"error","evidence":critic.details.get("finding_evidence",{}).get(x,{})} for x in critic.hard_violations],"warnings":critic.warnings,"checks":critic.checks,"details":critic.details},"stress_tests":evaluation.stress_simulation.model_dump(mode="json") if evaluation.stress_simulation else None,"technical_metrics":evaluation.plan.provenance}
  selected=strategies.get(recommended or "",{});status="completed" if recommended else "completed_with_no_feasible_recommendation"
  # Retain the exact selector inputs as downstream assistant metadata.  This
  # neither changes the optimizer nor reconstructs a rule at read time.
  strategy_selection={"rule":result.provenance.get("recommendation_rule"),"selected_strategy":recommended,"eligible_candidates":sorted(name for name,candidate in strategies.items() if candidate.get("is_feasible") and candidate.get("purchase_cost") is not None)}
  reasons=[]
  for item in selected.get("items",[]):
   if item.get("pack_count",0) and item.get("order_quantity",0) > 0: reasons.append({"code":"PACK_SIZE_ROUNDING","entity_id":item.get("ingredient_id"),"evidence":{"pack_size":item.get("pack_size"),"final_order_quantity":item.get("order_quantity")}})
  top_metrics=selected.get("business_metrics") if selected else build_business_metrics(purchase_cost=None,simulation=None,recommended=False)
  return {"decision_run_id":rid,"store_id":store,"as_of_date":forecast.cutoff_date.isoformat(),"horizon_days":forecast.horizon_days,"status":status,"engine_mode":mode,"recommended_strategy":recommended,"business_metrics":top_metrics,"recommended_plan":{"items":selected.get("items",[])},"ingredient_demand":[{"ingredient_id":x.ingredient_id,"target_date":x.target_date.isoformat(),"unit":x.unit,"p25":float(x.p25),"p50":float(x.p50),"p75":float(x.p75),"contributions":json.loads(x.contributions_json)} for x in demands],"inventory_risk":baseline.model_dump(mode="json"),"strategies":strategies,"strategy_selection":strategy_selection,"stress_tests":selected.get("stress_tests") or [],"critic":DecisionPlanningService._package_critic(strategies,recommended),"reason_codes":reasons,"warnings":sorted(warnings),"technical_metrics":{"scenario_count":len(request.demand_scenarios),"scenario_count_requested":scenario_metadata.get("scenario_count_requested"),"scenario_count_generated":scenario_metadata.get("scenario_count_generated"),"unique_scenario_count":scenario_metadata.get("unique_scenario_count"),"effective_scenario_count":scenario_metadata.get("effective_scenario_count"),"scenario_method":scenario_metadata.get("method","quantile_design_fallback"),"random_seed":request.seed,"optimizer_type":result.provenance["candidate_engine"],"cvar_alpha":None,"core_version":"local","stochastic_saa_enabled":request.stochastic,"stochastic_fallback_reason":scenario_metadata.get("stochastic_fallback_reason"),"risk_evaluation_status":request.risk_evaluation_metadata.get("status"),"risk_evaluation_sample_count":(len(request.demand_scenarios) if request.stochastic else len(request.risk_demand_scenarios)),"baseline_engine":"lot_level_fefo_v1","scenario_diagnostics":scenario_metadata.get("diagnostics",{}),"forecast_trace":forecast_trace or {},"shortage_economics":shortage_economics or {}}}
