"""catalog api foundation

Revision ID: 20260728_0005
Revises: 20260728_0004
Create Date: 2026-07-28 22:21:24.748061
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260728_0005'
down_revision: Union[str, None] = '20260728_0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients') as batch:
        batch.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch.create_check_constraint('ck_ingredients_version', 'version >= 1')
        batch.create_index('ix_ingredients_store_active', ['store_id', 'active'], unique=False)
    with op.batch_alter_table('products') as batch:
        batch.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch.create_check_constraint('ck_products_version', 'version >= 1')
        batch.create_index('ix_products_store_active', ['store_id', 'active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products') as batch:
        batch.drop_index('ix_products_store_active')
        batch.drop_constraint('ck_products_version', type_='check')
        batch.drop_column('version')
    with op.batch_alter_table('ingredients') as batch:
        batch.drop_index('ix_ingredients_store_active')
        batch.drop_constraint('ck_ingredients_version', type_='check')
        batch.drop_column('version')
    # ### end Alembic commands ###
