"""import to business persistence

Revision ID: 20260728_0004
Revises: 20260728_0003
Create Date: 2026-07-28 21:48:28.743963
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260728_0004'
down_revision: Union[str, None] = '20260728_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('business_persisted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('import_jobs', sa.Column('business_schema_version', sa.String(length=32), nullable=True))
    op.add_column('import_jobs', sa.Column('business_write_summary_json', sa.Text(), nullable=True))
    with op.batch_alter_table('inventory_lots') as batch:
        batch.add_column(sa.Column('reconciliation_key', sa.String(length=64), nullable=True))
        batch.create_unique_constraint('uq_inventory_lot_reconciliation', ['store_id', 'reconciliation_key'])
    with op.batch_alter_table('purchase_receipts') as batch:
        batch.add_column(sa.Column('business_key_hash', sa.String(length=64), nullable=True))
        batch.create_unique_constraint('uq_receipt_business_key', ['store_id', 'business_key_hash'])
    with op.batch_alter_table('sales_daily') as batch:
        batch.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch.add_column(sa.Column('natural_key_hash', sa.String(length=64), nullable=True))
        batch.create_unique_constraint('uq_sales_natural_key', ['store_id', 'date', 'product_id', 'promotion'])
    with op.batch_alter_table('usage_daily') as batch:
        batch.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch.add_column(sa.Column('natural_key_hash', sa.String(length=64), nullable=True))
        batch.create_unique_constraint('uq_usage_natural_key', ['store_id', 'date', 'ingredient_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_daily') as batch:
        batch.drop_constraint('uq_usage_natural_key', type_='unique')
        batch.drop_column('natural_key_hash')
        batch.drop_column('updated_at')
    with op.batch_alter_table('sales_daily') as batch:
        batch.drop_constraint('uq_sales_natural_key', type_='unique')
        batch.drop_column('natural_key_hash')
        batch.drop_column('updated_at')
    with op.batch_alter_table('purchase_receipts') as batch:
        batch.drop_constraint('uq_receipt_business_key', type_='unique')
        batch.drop_column('business_key_hash')
    with op.batch_alter_table('inventory_lots') as batch:
        batch.drop_constraint('uq_inventory_lot_reconciliation', type_='unique')
        batch.drop_column('reconciliation_key')
    op.drop_column('import_jobs', 'business_write_summary_json')
    op.drop_column('import_jobs', 'business_schema_version')
    op.drop_column('import_jobs', 'business_persisted_at')
    # ### end Alembic commands ###
