"""production behavior completion

Revision ID: 20260728_0007
Revises: 20260728_0006
Create Date: 2026-07-29 00:01:02.660108
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260728_0007'
down_revision: Union[str, None] = '20260728_0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('plan_run_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('order_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('moq', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('pack_size', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['plan_run_id'], ['plan_runs.plan_run_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_recommendations_plan_run_id'), 'recommendations', ['plan_run_id'], unique=False)
    op.create_index(op.f('ix_recommendations_store_id'), 'recommendations', ['store_id'], unique=False)
    op.add_column('inventory_lots', sa.Column('last_counted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_receipts', sa.Column('external_record_id', sa.String(length=255), nullable=True))
    op.add_column('purchase_receipts', sa.Column('inventory_effect', sa.String(length=32), nullable=False))
    op.add_column('purchase_receipts', sa.Column('po_id', sa.String(length=36), nullable=True))
    op.add_column('purchase_receipts', sa.Column('po_line_id', sa.String(length=36), nullable=True))
    op.add_column('sales_daily', sa.Column('external_record_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_daily', 'external_record_id')
    op.drop_column('purchase_receipts', 'po_line_id')
    op.drop_column('purchase_receipts', 'po_id')
    op.drop_column('purchase_receipts', 'inventory_effect')
    op.drop_column('purchase_receipts', 'external_record_id')
    op.drop_column('inventory_lots', 'last_counted_at')
    op.drop_index(op.f('ix_recommendations_store_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_plan_run_id'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
