"""operational api completion

Revision ID: 20260728_0006
Revises: 20260728_0005
Create Date: 2026-07-28 23:51:20.370064
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260728_0006'
down_revision: Union[str, None] = '20260728_0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_periods',
    sa.Column('budget_period_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('monthly_budget', sa.Integer(), nullable=False),
    sa.Column('reserved_budget', sa.Integer(), nullable=False),
    sa.Column('spent_budget', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('budget_period_id'),
    sa.UniqueConstraint('store_id', 'period', name='uq_budget_store_period')
    )
    op.create_index(op.f('ix_budget_periods_store_id'), 'budget_periods', ['store_id'], unique=False)
    op.create_table('forecast_runs',
    sa.Column('forecast_run_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('cutoff_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('quantiles_json', sa.Text(), nullable=False),
    sa.Column('scope_json', sa.Text(), nullable=False),
    sa.Column('use_latest_calendar', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('engine_status', sa.String(length=40), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('calibrator_version', sa.String(length=128), nullable=True),
    sa.Column('input_snapshot_json', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('forecast_run_id')
    )
    op.create_index(op.f('ix_forecast_runs_store_id'), 'forecast_runs', ['store_id'], unique=False)
    op.create_table('plan_runs',
    sa.Column('plan_run_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('forecast_run_id', sa.String(length=36), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('budget_limit', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('include_open_purchase_orders', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('engine_status', sa.String(length=40), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('input_snapshot_json', sa.Text(), nullable=True),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.forecast_run_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('plan_run_id')
    )
    op.create_index(op.f('ix_plan_runs_store_id'), 'plan_runs', ['store_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('po_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('plan_run_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('budget_after', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_run_id'], ['plan_runs.plan_run_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_index(op.f('ix_purchase_orders_store_id'), 'purchase_orders', ['store_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('po_line_id', sa.String(length=36), nullable=False),
    sa.Column('po_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('ordered_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('moq', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('pack_size', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], ),
    sa.PrimaryKeyConstraint('po_line_id')
    )
    op.create_index(op.f('ix_purchase_order_lines_po_id'), 'purchase_order_lines', ['po_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_order_lines_po_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_purchase_orders_store_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_plan_runs_store_id'), table_name='plan_runs')
    op.drop_table('plan_runs')
    op.drop_index(op.f('ix_forecast_runs_store_id'), table_name='forecast_runs')
    op.drop_table('forecast_runs')
    op.drop_index(op.f('ix_budget_periods_store_id'), table_name='budget_periods')
    op.drop_table('budget_periods')
    # ### end Alembic commands ###
