"""canonical business schema

Revision ID: 20260728_0003
Revises: 20260728_0002
Create Date: 2026-07-28 21:08:09.525128
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260728_0003'
down_revision: Union[str, None] = '20260728_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('ingredient', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('base_unit', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("base_unit IN ('kg','g','lít','ml','cái')", name='ck_ingredients_base_unit'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('ingredient_id'),
    sa.UniqueConstraint('store_id', 'normalized_name', name='uq_ingredients_store_name'),
    sa.UniqueConstraint('store_id', 'sku', name='uq_ingredients_store_sku')
    )
    op.create_index('ix_ingredients_normalized_name', 'ingredients', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_ingredients_store_id'), 'ingredients', ['store_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price IS NULL OR price >= 0', name='ck_products_price'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('store_id', 'normalized_name', name='uq_products_store_name'),
    sa.UniqueConstraint('store_id', 'sku', name='uq_products_store_sku')
    )
    op.create_index('ix_products_normalized_name', 'products', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_products_store_id'), 'products', ['store_id'], unique=False)
    op.create_table('store_settings',
    sa.Column('setting_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('monthly_budget', sa.Integer(), nullable=False),
    sa.Column('forecast_horizon', sa.Integer(), nullable=False),
    sa.Column('default_strategy', sa.String(length=16), nullable=False),
    sa.Column('safety_policy_json', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("default_strategy IN ('economy','balanced','safe')", name='ck_store_settings_strategy'),
    sa.CheckConstraint('forecast_horizon >= 1', name='ck_store_settings_horizon'),
    sa.CheckConstraint('monthly_budget >= 0', name='ck_store_settings_budget'),
    sa.CheckConstraint('version >= 1', name='ck_store_settings_version'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('supplier_id'),
    sa.UniqueConstraint('store_id', 'normalized_name', name='uq_suppliers_store_name')
    )
    op.create_index('ix_suppliers_normalized_name', 'suppliers', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_suppliers_store_id'), 'suppliers', ['store_id'], unique=False)
    op.create_table('ingredient_aliases',
    sa.Column('alias_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('alias_id'),
    sa.UniqueConstraint('store_id', 'normalized_alias', name='uq_aliases_store_alias')
    )
    op.create_index(op.f('ix_ingredient_aliases_ingredient_id'), 'ingredient_aliases', ['ingredient_id'], unique=False)
    op.create_table('calendar_features',
    sa.Column('calendar_feature_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('is_store_closed', sa.Boolean(), nullable=False),
    sa.Column('is_promotion', sa.Boolean(), nullable=False),
    sa.Column('promotion_name', sa.String(length=255), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('rainfall', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_import_id', sa.String(length=36), nullable=True),
    sa.Column('source_profile_id', sa.String(length=36), nullable=True),
    sa.Column('source_row_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_import_id'], ['import_jobs.import_id'], ),
    sa.ForeignKeyConstraint(['source_profile_id'], ['import_sheet_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('calendar_feature_id'),
    sa.UniqueConstraint('store_id', 'date', name='uq_calendar_store_date')
    )
    op.create_index('ix_calendar_date', 'calendar_features', ['date'], unique=False)
    op.create_table('inventory_lots',
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('batch_code', sa.String(length=128), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('initial_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_import_id', sa.String(length=36), nullable=True),
    sa.Column('source_profile_id', sa.String(length=36), nullable=True),
    sa.Column('source_row_hash', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("unit IN ('kg', 'g', 'lít', 'ml', 'cái')", name='ck_inventory_lot_unit'),
    sa.CheckConstraint('expiry_date IS NULL OR expiry_date >= received_date', name='ck_inventory_lot_dates'),
    sa.CheckConstraint('initial_quantity >= 0', name='ck_inventory_lot_quantity'),
    sa.CheckConstraint('unit_cost IS NULL OR unit_cost >= 0', name='ck_inventory_lot_cost'),
    sa.CheckConstraint('version >= 1', name='ck_inventory_lot_version'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['source_import_id'], ['import_jobs.import_id'], ),
    sa.ForeignKeyConstraint(['source_profile_id'], ['import_sheet_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('lot_id'),
    sa.UniqueConstraint('source_import_id', 'source_profile_id', 'source_row_hash', name='uq_inventory_lot_provenance')
    )
    op.create_index('ix_inventory_lots_expiry_date', 'inventory_lots', ['expiry_date'], unique=False)
    op.create_index('ix_inventory_lots_store_ingredient', 'inventory_lots', ['store_id', 'ingredient_id'], unique=False)
    op.create_table('purchase_receipts',
    sa.Column('receipt_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('batch_code', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=True),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('source_row_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("unit IN ('kg', 'g', 'lít', 'ml', 'cái')", name='ck_receipt_unit'),
    sa.CheckConstraint('expiry_date IS NULL OR expiry_date >= receipt_date', name='ck_receipt_dates'),
    sa.CheckConstraint('quantity >= 0', name='ck_receipt_quantity'),
    sa.CheckConstraint('unit_cost IS NULL OR unit_cost >= 0', name='ck_receipt_cost'),
    sa.ForeignKeyConstraint(['import_id'], ['import_jobs.import_id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['import_sheet_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('receipt_id'),
    sa.UniqueConstraint('import_id', 'profile_id', 'source_row_hash', name='uq_receipt_provenance')
    )
    op.create_index('ix_receipts_ingredient_date', 'purchase_receipts', ['ingredient_id', 'receipt_date'], unique=False)
    op.create_index('ix_receipts_store_date', 'purchase_receipts', ['store_id', 'receipt_date'], unique=False)
    op.create_table('recipe_versions',
    sa.Column('recipe_version_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_import_id', sa.String(length=36), nullable=True),
    sa.Column('source_profile_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_recipe_dates'),
    sa.CheckConstraint('version >= 1', name='ck_recipe_version'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['source_import_id'], ['import_jobs.import_id'], ),
    sa.ForeignKeyConstraint(['source_profile_id'], ['import_sheet_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('recipe_version_id'),
    sa.UniqueConstraint('product_id', 'version', name='uq_recipe_product_version')
    )
    op.create_index('ix_recipe_product_effective', 'recipe_versions', ['product_id', 'effective_from'], unique=False)
    op.create_table('sales_daily',
    sa.Column('sales_record_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('promotion', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=True),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('source_row_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_sales_quantity'),
    sa.CheckConstraint('unit_price IS NULL OR unit_price >= 0', name='ck_sales_price'),
    sa.ForeignKeyConstraint(['import_id'], ['import_jobs.import_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['import_sheet_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('sales_record_id'),
    sa.UniqueConstraint('import_id', 'profile_id', 'source_row_hash', name='uq_sales_provenance')
    )
    op.create_index('ix_sales_product_date', 'sales_daily', ['product_id', 'date'], unique=False)
    op.create_index('ix_sales_store_date', 'sales_daily', ['store_id', 'date'], unique=False)
    op.create_table('supplier_ingredient_terms',
    sa.Column('constraint_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.Column('moq', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('pack_size', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_import_id', sa.String(length=36), nullable=True),
    sa.Column('source_profile_id', sa.String(length=36), nullable=True),
    sa.Column('source_row_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("unit IN ('kg', 'g', 'lít', 'ml', 'cái')", name='ck_supplier_term_unit'),
    sa.CheckConstraint('capacity IS NULL OR capacity >= 0', name='ck_supplier_term_capacity'),
    sa.CheckConstraint('unit_cost >= 0 AND moq >= 0 AND pack_size > 0 AND lead_time_days >= 0 AND safety_stock >= 0', name='ck_supplier_term_values'),
    sa.CheckConstraint('version >= 1', name='ck_supplier_term_version'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['source_import_id'], ['import_jobs.import_id'], ),
    sa.ForeignKeyConstraint(['source_profile_id'], ['import_sheet_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('constraint_id'),
    sa.UniqueConstraint('supplier_id', 'ingredient_id', 'version', name='uq_supplier_term_version')
    )
    op.create_index('ix_supplier_terms_store_ingredient', 'supplier_ingredient_terms', ['store_id', 'ingredient_id'], unique=False)
    op.create_table('usage_daily',
    sa.Column('usage_record_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=True),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('source_row_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("unit IN ('kg', 'g', 'lít', 'ml', 'cái')", name='ck_usage_unit'),
    sa.CheckConstraint('quantity >= 0', name='ck_usage_quantity'),
    sa.ForeignKeyConstraint(['import_id'], ['import_jobs.import_id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['import_sheet_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('usage_record_id'),
    sa.UniqueConstraint('import_id', 'profile_id', 'source_row_hash', name='uq_usage_provenance')
    )
    op.create_index('ix_usage_ingredient_date', 'usage_daily', ['ingredient_id', 'date'], unique=False)
    op.create_index('ix_usage_store_date', 'usage_daily', ['store_id', 'date'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('movement_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('movement_type', sa.String(length=40), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('source_import_id', sa.String(length=36), nullable=True),
    sa.Column('source_profile_id', sa.String(length=36), nullable=True),
    sa.Column('source_row_hash', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("movement_type IN ('opening_balance','receipt','physical_count_adjustment','waste','expiry','manual_adjustment','usage','purchase_order_inbound')", name='ck_inventory_movement_type'),
    sa.CheckConstraint("unit IN ('kg', 'g', 'lít', 'ml', 'cái')", name='ck_inventory_movement_unit'),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lots.lot_id'], ),
    sa.ForeignKeyConstraint(['source_import_id'], ['import_jobs.import_id'], ),
    sa.ForeignKeyConstraint(['source_profile_id'], ['import_sheet_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('movement_id'),
    sa.UniqueConstraint('source_import_id', 'source_profile_id', 'source_row_hash', name='uq_inventory_movement_provenance')
    )
    op.create_index('ix_inventory_movements_lot_occurred', 'inventory_movements', ['lot_id', 'occurred_at'], unique=False)
    op.create_table('recipe_lines',
    sa.Column('recipe_line_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_version_id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("unit IN ('kg', 'g', 'lít', 'ml', 'cái')", name='ck_recipe_line_unit'),
    sa.CheckConstraint('quantity > 0', name='ck_recipe_line_quantity'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['recipe_version_id'], ['recipe_versions.recipe_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_line_id'),
    sa.UniqueConstraint('recipe_version_id', 'ingredient_id', name='uq_recipe_line_ingredient')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_lines')
    op.drop_index('ix_inventory_movements_lot_occurred', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('ix_usage_store_date', table_name='usage_daily')
    op.drop_index('ix_usage_ingredient_date', table_name='usage_daily')
    op.drop_table('usage_daily')
    op.drop_index('ix_supplier_terms_store_ingredient', table_name='supplier_ingredient_terms')
    op.drop_table('supplier_ingredient_terms')
    op.drop_index('ix_sales_store_date', table_name='sales_daily')
    op.drop_index('ix_sales_product_date', table_name='sales_daily')
    op.drop_table('sales_daily')
    op.drop_index('ix_recipe_product_effective', table_name='recipe_versions')
    op.drop_table('recipe_versions')
    op.drop_index('ix_receipts_store_date', table_name='purchase_receipts')
    op.drop_index('ix_receipts_ingredient_date', table_name='purchase_receipts')
    op.drop_table('purchase_receipts')
    op.drop_index('ix_inventory_lots_store_ingredient', table_name='inventory_lots')
    op.drop_index('ix_inventory_lots_expiry_date', table_name='inventory_lots')
    op.drop_table('inventory_lots')
    op.drop_index('ix_calendar_date', table_name='calendar_features')
    op.drop_table('calendar_features')
    op.drop_index(op.f('ix_ingredient_aliases_ingredient_id'), table_name='ingredient_aliases')
    op.drop_table('ingredient_aliases')
    op.drop_index(op.f('ix_suppliers_store_id'), table_name='suppliers')
    op.drop_index('ix_suppliers_normalized_name', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('store_settings')
    op.drop_index(op.f('ix_products_store_id'), table_name='products')
    op.drop_index('ix_products_normalized_name', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_ingredients_store_id'), table_name='ingredients')
    op.drop_index('ix_ingredients_normalized_name', table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
